const {
	APPWRITE_PROJECT_ID,
	APPWRITE_API_KEY,
	APPWRITE_DB_ID,
	APPWRITE_DB_PATIENT_COLLECTION_ID,
	APPWRITE_DB_DOCTOR_COLLECTION_ID,
	APPWRITE_DB_APPOINTMENT_COLLECTION_ID,
	NEXT_PUBLIC_BUCKET_ID,
	NEXT_PUBLIC_ENDPOINT,
} = process.env
