export const Route = {
	HOME: '/',
	SIGN_IN: '/sign-in',
	SIGN_UP: '/sign-up',
	DASHBOARD: '/dashboard',
	DASHBOARD_PATIENT: '/dashboard',
	DASHBOARD_DOCTOR: '/dashboard',
	DASHBOARD_ADMIN: '/dashboard',
	PATIENTS: '/patients',
	REGISTER: '/register',
	CREATE_APPOINTMENT: '/create-appointment',
	SUCCESS: '/success',
	USER_VERIFICATION_RESULT: 'http://localhost:3000/user-verification-result',
	USER_VERIFICATION_PENDING: '/user-verification-pending',
}

export const IconPath = {
	LOGO_FULL: '/assets/icons/logo-full.svg',
	LOGO_FULL_BLACK: '/assets/icons/logo-full-black.svg',
	LOGO: '/assets/icons/logo-icon.svg',
	USER: '/assets/icons/user.svg',
	EMAIL: '/assets/icons/email.svg',
	PHONE: '/assets/icons/phone.svg',
	LOADER: '/assets/icons/loader.svg',
	UPLOAD: '/assets/icons/upload.svg',
	UPLOAD_ANIM: '/assets/gifs/upload.gif',
	SUCCESS_ANIM: '/assets/gifs/success.gif',
	LOADING_ANIM: '/assets/gifs/loading2.gif',
	FAILED_ANIM: '/assets/gifs/failed.gif',
	CALENDAR: '/assets/icons/calendar.svg',
	CLOSE: '/assets/icons/close.svg',
	SCHEDULED: '/assets/icons/scheduled.svg',
	PENDING: '/assets/icons/pending.svg',
	CANCELLED: '/assets/icons/cancelled.svg',
	FINISHED: '/assets/icons/finished.svg',
	PASSWORD: '/assets/icons/password.svg',
	SUN: '/assets/icons/sun.svg',
	MOON: '/assets/icons/moon.svg',
	SIGN_OUT: '/assets/icons/sign-out.svg',
	SETTINGS: '/assets/icons/settings.svg',
	PROFILE: '/assets/icons/profile.svg',
	ACCOUNT: '/assets/icons/account.svg',
	DASHBOARD: '/assets/icons/dashboard.svg',
	TEST_RESULT: '/assets/icons/test-result.svg',
	TREATMENT_HISTORY: '/assets/icons/treatment-history.svg',
	APPOINTMENT: '/assets/icons/appointment.svg',
	CHAT: '/assets/icons/chat.svg',
	DOC_MED: '/assets/icons/doc-med.svg',
	BICYCLE: '/assets/icons/bicycle.svg',
	BELL: '/assets/icons/bell.svg',
	DEVICE: '/assets/icons/device.svg',
	CASH: '/assets/icons/cash.svg',
	DOT: '/assets/icons/dot.svg',
	RELOAD: '/assets/icons/reload.svg',
	SEARCH: '/assets/icons/search.svg',
	EYE: '/assets/icons/eye.svg',
	EYE_OFF: '/assets/icons/eye-off.svg',
}

export const ImagePath = {
	SIGN_IN: '/assets/images/onboarding3-img.jpg',
	SIGN_UP: '/assets/images/onboarding1-img.jpg',
	REGISTER_PAGE: '/assets/images/register-img.jpg',
	NEW_APPOINTMENT_PAGE: '/assets/images/appointment-img.jpg',
	USER_NOT_VERIFIED: '/assets/images/user-not-verified.png',
	PATIENT_CREATE: '/assets/images/patient-create.png',
	APPOINTMENT_CREATE: '/assets/images/appointment-create.png',
}

export const VideoPath = {
	// HOME_PAGE: 'https://healthcare-clinic.s3.eu-north-1.amazonaws.com/doctors_qhd.mp4',
	HOME_PAGE: 'https://cloud.appwrite.io/v1/storage/buckets/66d9d9fd00319d398b25/files/6713cf56001eecf48757/view?project=66d9d5c5000d0b96a418&project=66d9d5c5000d0b96a418&mode=admin',
}

export const DoctorPath = {
	GREEN: '/assets/images/dr-green.png',
	CAMERON: '/assets/images/dr-cameron.png',
	LIVINGSTON: '/assets/images/dr-livingston.png',
	PETER: '/assets/images/dr-peter.png',
	POWELL: '/assets/images/dr-powell.png',
	REMIREZ: '/assets/images/dr-remirez.png',
	LEE: '/assets/images/dr-lee.png',
	CRUZ: '/assets/images/dr-cruz.png',
	SHARMA: '/assets/images/dr-sharma.png',
}


